[build]
  base = "."
  command = "cd frontend-restaurante && npm install && npm run build"
  publish = "frontend-restaurante/out"

[build.environment]
  NODE_VERSION = "22"
  NPM_VERSION = "10"
  NODE_ENV = "production"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  directory = "api"
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
